### ISSUE TITLE
Models not generated at end of step 3

### ISSUE THREAD

**Issue by lorensr** [apollographql/apollo-android-tutorial#1]
I'm unable to do this section:

https://www.apollographql.com/docs/android/tutorial/03-write-your-first-query/#examine-generated-code

because there is no `build/generated/` directory. 

![image](https://user-images.githubusercontent.com/251288/86860022-06333980-c092-11ea-9020-bac419c9864a.png)

I've tried `Build > Run Generated Sources Gradle Tasks`, `Build > Rebuild Project`, and running on simulator. Repro:

https://github.com/lorensr/apollo-android-tutorial/tree/step3

**Comment by martinbonnin** [comment]
Hi @lorensr 👋  ! Very sorry I missed this. If this issue is still valid, you should be able to find the sources in the `app/build` folder, not the root `build` folder. Or using Android Studio "Navigate" feature.
