### ISSUE TITLE
Cannot generate Kotlin models

### ISSUE THREAD

**Issue by ksalil** [apollographql/apollo-android-tutorial#3]
Tutorial - https://www.apollographql.com/docs/android/tutorial/03-write-your-first-query/

I am on the "initial" branch and cannot generate Kotlin models at the end of step 3.
I have tried rebuilding the project, running generateApolloSources , ran the app on a device.
Apollo version - 2.5.5

![image](https://user-images.githubusercontent.com/1083630/114079749-91876880-9878-11eb-9811-b2ebd8fb0eaf.png)
![image](https://user-images.githubusercontent.com/1083630/114079840-a82dbf80-9878-11eb-91ac-801a16c6ebb0.png)

**Comment by martinbonnin** [comment]
Hi 👋 ! What is the output of `generateApolloSources`? Do it find sources or does it show `NO-SOURCE`? 

Also could you push  your fork to github, that might just be easier to investigate.

**Comment by ksalil** [comment]
Hi,
Output for `generateApolloSources`


`Selected primary task ':app:generateApolloSources' from project :app
file or directory 'AndroidStudioProjects/apollo-android-tutorial/app/src/test/graphql', not found
file or directory 'AndroidStudioProjects/apollo-android-tutorial/app/src/testDebug/graphql', not found
file or directory 'AndroidStudioProjects/apollo-android-tutorial/app/src/main/graphql', not found
file or directory 'AndroidStudioProjects/apollo-android-tutorial/app/src/debug/graphql', not found
file or directory 'AndroidStudioProjects/apollo-android-tutorial/app/src/main/graphql', not found
file or directory 'AndroidStudioProjects/apollo-android-tutorial/app/src/release/graphql', not found
file or directory 'AndroidStudioProjects/apollo-android-tutorial/app/src/androidTest/graphql', not found
file or directory 'AndroidStudioProjects/apollo-android-tutorial/app/src/androidTestDebug/graphql', not found
file or directory 'AndroidStudioProjects/apollo-android-tutorial/app/src/test/graphql', not found
file or directory 'AndroidStudioProjects/apollo-android-tutorial/app/src/testRelease/graphql', not found
`

The command to download the schema creates the graphql directory outside the app module and the gradle task expects it to be inside the app module.

`mkdir -p app/src/main/graphql/com/example/rocketreserver/
./gradlew :app:downloadApolloSchema --endpoint='https://apollo-fullstack-tutorial.herokuapp.com/' --schema='src/main/graphql/com/example/rocketreserver/schema.json'
`

I moved the graphql directory to app and it works now.
